### ISSUE TITLE
Can't open the directories

### ISSUE THREAD

**Issue by airpoint** [tknorris/tknorris-beta-repo#8]
Hey, I felt like experimenting a bit and tried the SALTS beta on my Kodi 15.2 OSX. Didn't get too far unfortunately as you can see from the log below—it doesn't let me go into Movies (nor TVShows).

I know this is WiP so not sure if I should even comment here at all, so feel free to ignore this :)

```
22:30:12 T:4580900864  NOTICE: -->Python Interpreter Initialized<--
22:30:12 T:4580900864  NOTICE: Stream All The Sources: Version: |1.0.73| Queries: |{'mode': 'main'}|
22:30:12 T:4580900864  NOTICE: Stream All The Sources: Args: |['plugin://plugin.video.salts/', '11', '']|
22:30:12 T:4580900864  NOTICE: Stream All The Sources: Calling |main_menu| for mode |main| with pos args |[]| and kwargs |{}|
22:30:12 T:4634853376  NOTICE: Thread BackgroundLoader start, auto delete: false
22:30:18 T:4505792512  NOTICE: Thread LanguageInvoker start, auto delete: false
22:30:18 T:4505792512  NOTICE: -->Python Interpreter Initialized<--
22:30:18 T:4505792512  NOTICE: Stream All The Sources: Version: |1.0.73| Queries: |{'section': 'Movies', 'mode': 'browse'}|
22:30:18 T:4505792512  NOTICE: Stream All The Sources: Args: |['plugin://plugin.video.salts/', '12', '?mode=browse&section=Movies']|
22:30:18 T:4505792512  NOTICE: Stream All The Sources: Calling |browse_menu| for mode |browse| with pos args |['Movies']| and kwargs |{}|
22:30:18 T:4505792512 WARNING: Stream All The Sources: Retrying (2/5) SQL: SELECT timestamp, response FROM url_cache WHERE url = ? and data=?
22:30:18 T:4505792512 WARNING: Stream All The Sources: Retrying (3/5) SQL: SELECT timestamp, response FROM url_cache WHERE url = ? and data=?
22:30:18 T:4505792512 WARNING: Stream All The Sources: Retrying (4/5) SQL: SELECT timestamp, response FROM url_cache WHERE url = ? and data=?
22:30:18 T:4505792512 WARNING: Stream All The Sources: Retrying (5/5) SQL: SELECT timestamp, response FROM url_cache WHERE url = ? and data=?
22:30:18 T:4505792512   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'sqlite3.OperationalError'>
                                            Error Contents: no such column: data
                                            Traceback (most recent call last):
                                              File "/Users/airpoint/Library/Application Support/Kodi/addons/plugin.video.salts/default.py", line 2301, in <module>
                                                sys.exit(main())
                                              File "/Users/airpoint/Library/Application Support/Kodi/addons/plugin.video.salts/default.py", line 2295, in main
                                                url_dispatcher.dispatch(mode, queries)
                                              File "/Users/airpoint/Library/Application Support/Kodi/addons/plugin.video.salts/salts_lib/url_dispatcher.py", line 80, in dispatch
                                                self.func_registry[mode](*args, **kwargs)
                                              File "/Users/airpoint/Library/Application Support/Kodi/addons/plugin.video.salts/default.py", line 227, in browse_menu
                                                add_section_lists(section)
                                              File "/Users/airpoint/Library/Application Support/Kodi/addons/plugin.video.salts/default.py", line 265, in add_section_lists
                                                add_other_list_item(MODES.BROWSE, section, other_list)
                                              File "/Users/airpoint/Library/Application Support/Kodi/addons/plugin.video.salts/default.py", line 565, in add_other_list_item
                                                header = trakt_api.get_list_header(other_list[1], other_list[0], auth)
                                              File "/Users/airpoint/Library/Application Support/Kodi/addons/plugin.video.salts/salts_lib/trakt_api.py", line 93, in get_list_header
                                                return self.__call_trakt(url, auth=auth)
                                              File "/Users/airpoint/Library/Application Support/Kodi/addons/plugin.video.salts/salts_lib/trakt_api.py", line 373, in __call_trakt
                                                created, cached_result = db_connection.get_cached_url(url, json_data, db_cache_limit)
                                              File "/Users/airpoint/Library/Application Support/Kodi/addons/plugin.video.salts/salts_lib/db_utils.py", line 125, in get_cached_url
                                                rows = self.__execute(sql, (url, data))
                                              File "/Users/airpoint/Library/Application Support/Kodi/addons/plugin.video.salts/salts_lib/db_utils.py", line 410, in __execute
                                                cur.execute(sql, params)
                                            OperationalError: no such column: data
                                            -->End of Python script error report<--
22:30:18 T:140735217017600   ERROR: GetDirectory - Error getting plugin://plugin.video.salts/?mode=browse&section=Movies
22:30:18 T:140735217017600   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.salts/?mode=browse&section=Movies) failed
22:30:18 T:4505792512  NOTICE: Thread LanguageInvoker start, auto delete: false
22:30:18 T:4505792512  NOTICE: -->Python Interpreter Initialized<--
22:30:18 T:4505792512  NOTICE: Stream All The Sources: Version: |1.0.73| Queries: |{'mode': 'main'}|
22:30:18 T:4505792512  NOTICE: Stream All The Sources: Args: |['plugin://plugin.video.salts/', '13', '']|
22:30:18 T:4505792512  NOTICE: Stream All The Sources: Calling |main_menu| for mode |main| with pos args |[]| and kwargs |{}|
```

**Comment by tknorris** [comment]
The problem is you still have the salts release db while trying to use the beta. You need to delete the file called "saltscache.db". Where it is depends on your platform. If you are in kodi, you can use the File Manager and add a source with path "special://database" and the file will be in that source.

**Comment by airpoint** [comment]
Yep, that worked nicely. Thanks for that!
Also, this beta is just so **much faster** than the release version! So thanks for that too.

Btw. I'm loving the 'Requested n sources from...' on the sources search window—it's a great UX improvement IMO. Good job.

Cheers
